apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-harbor
  namespace: platform
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - nginx.platform.local
      secretName: nginx-harbor-tls
  rules:
    - host: nginx.platform.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-harbor
                port:
                  number: 80
