[bastion]
192.168.1.20

[k8s_master]
192.168.1.21

[k8s_workers]
192.168.1.22
192.168.1.23

[harbor]
192.168.1.24

[security]
192.168.1.25

[monitoring]
192.168.1.26

[k8s:children]
k8s_master
k8s_workers

[all:vars]
ansible_user=devops
ansible_become=true
ansible_become_method=sudo
